version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:80"
    restart: unless-stopped
    container_name: frontend
    # If you need to connect to a backend running outside the container
    # environment:
    #   - VITE_API_URL=http://localhost:5000
  
  # If you want to add your backend as well
  # backend:
  #   build: ../Musicly-backend  # Adjust path as needed
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
  #   container_name: musicly-backend